version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/development_database
    depends_on:
      - mongo
    networks:
      - app

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cms.gabrielhalus.com.conf:/etc/nginx/conf.d/cms.gabrielhalus.com.conf:ro
    networks:
      - app

networks:
  app:

volumes:
  mongo-data:
